//This is the entry-point
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/1

### To create a new note
POST http://localhost:3001/api/notes
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 sGMT"
}