//This is the entry-point
GET http://localhost:3001/api/notes


###
GET http://localhost:3001/api/notes/60d44f1eeea68715ecfaa1fd

### To create a new note
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content" : "content of the new note",
    "important" : true
}

### delete a note
DELETE http://localhost:3001/api/notes/1

### unknown default endpoint
GET http://localhost:3001/dsdsa
